name: Deploy to WordPress.org
on:
  release:
    types: [published]
jobs:
  tag:
    name: HENSHIN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Fix Git safe directory
        run: git config --global --add safe.directory /github/workspace

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: ${{ secrets.SLUG }}
