name: WPCS check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  phpcs:
    name: WPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - name: Install PHPCS + WPCS
        run: |
          composer global config allow-plugins.dealerdirect/phpcodesniffer-composer-installer true
          composer global require \
            squizlabs/php_codesniffer \
            wp-coding-standards/wpcs:"^3" \
            dealerdirect/phpcodesniffer-composer-installer \
            --no-progress
          echo "$HOME/.composer/vendor/bin" >> "$GITHUB_PATH"
      - name: WPCS check
        run: phpcs --standard=WordPress-Extra --ignore=vendor --report-json=./phpcs.json .
      - name: Update summary
        run: |
          npm i -g github:10up/phpcs-json-to-md
          phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
          cat phpcs.md >> $GITHUB_STEP_SUMMARY
        if: always()
